//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : NewModel
//  @ File Name : PhoneTypes.h
//  @ Date : 10.04.2018
//  @ Author : JefferyWA
//
//

#if !defined(_MODEL_H)
#define _MODEL_H
#include <string>;
using namespace std;

class Model {
private:
	string name;
	string os;
	bool browser;

  public:
	Model(string name, string os, bool browser) {
		this->name = name;
		this->os = os;
		this->browser = browser;
	}

	virtual void Show() {
		std::cout << name << " " << os << " " << browser;
	}

	void setName(string model_name)
	{
		name = model_name;
    }

	string getName() {
		return name;
	}

	void setOS(int model_os)
	{
		os = model_os;
	}

	int getOS() {
		return os;
	}

	void setBrowser(int model_browser)
	{
		browser = model_browser;
	}

	int getBrowser()
	{
		return browser;
	}

};



#endif  //_PRODUCT_H
