//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : NewModel
//  @ File Name : PhoneTypes.h
//  @ Date : 10.04.2018
//  @ Author : JefferyWA
//
//

#if !defined(_PHONE_H)
#define _PHONE_H

#include "Model.h"
#include "PhoneTypes.h";
class Phone : public Model {
public:
  Phone(string name, string os, bool browser, int type) : Model(name, os, browser)
  {
      this->type = type;
    }

    void setType(int PhoneTypes)
    {
        type = PhoneTypes;
    }

	int getType() {
		return type;
	};
private:
	int type;
};

#endif  //_COFFEE_H
