//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : NewModel
//  @ File Name : PhoneTypes.h
//  @ Date : 10.04.2018
//  @ Author : JefferyWA
//
//

#if !defined(_PHONETYPES_H)
#define _PHONETYPES_H


enum PhoneTypes {
	with_browser,
	without_browser
};

#endif  //_COFFEETYPES_H
