//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : NewModel
//  @ File Name : PhoneTypes.h
//  @ Date : 10.04.2018
//  @ Author : JefferyWA
//
//

#include " Phone.h"

void Phone::GetType() {

}

